spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod API"
  contactDetails:
    name: "Rene Reyes - Product Owner"
    email: "reyes@eazybank.com"
  onCallSupport:
    - (453) 453-1234
    - (453) 453-1345