spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA API"
  contactDetails:
    name: "Smith Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 666-1234
    - (666) 666-1345